const views=[...document.querySelectorAll('.view')],state={runId:null,etag:null,poll:null,session:null,results:null};
const show=id=>views.forEach(v=>v.classList.toggle('active',v.id===id));
const api=async(url,options={})=>{const response=await fetch(url,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}),body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.message||`Request failed (${response.status})`);return{body,response}};
const fail=(e,retryable=false)=>{clearTimeout(state.poll);document.querySelector('#error-message').textContent=e.message;document.querySelector('#retry-run').hidden=!(retryable&&state.runId);show('error')};
const create=async source=>(await api('/api/runs',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()+crypto.randomUUID()},body:JSON.stringify({handling_policy:document.querySelector('#retain-media').checked?'retain_and_enroll':'search_then_discard',source})})).body;
const openRun=id=>{state.runId=id;history.replaceState({},'',`/runs/${id}`);poll()};
async function poll(){try{const{body:r}=await api(`/api/runs/${state.runId}`);show('status');document.querySelector('#state-label').textContent=r.state.replaceAll('_',' ');document.querySelector('#status-detail').textContent=`Run ${r.run_id} · expires ${new Date(r.expires_at).toLocaleString()}`;document.querySelector('#cancel-run').hidden=!['awaiting_media','fetching','queued','detecting','awaiting_face_selection'].includes(r.state);if(r.state==='awaiting_face_selection')return groups();if(r.state==='succeeded')return r.outcome==='no_faces'?noFaces():results();if(['failed','cancelled','expired'].includes(r.state))return fail(new Error(r.error?.message||`Run ${r.state}.`),r.retryable);state.poll=setTimeout(poll,2500)}catch(e){fail(e)}}
document.querySelector('#url-form').addEventListener('submit',async e=>{e.preventDefault();try{openRun((await create({kind:'url',url:document.querySelector('#source-url').value})).run_id)}catch(x){fail(x)}});
document.querySelector('#upload-form').addEventListener('submit',async e=>{e.preventDefault();const file=document.querySelector('#source-file').files[0];if(!file)return;const cancel=document.querySelector('#cancel-upload');try{state.runId=(await create({kind:'upload',content_type:file.type,bytes:file.size})).run_id;state.session=(await api(`/api/runs/${state.runId}/upload-session`,{method:'POST',body:'{}'})).body.session_uri;cancel.hidden=false;const upload=await fetch(state.session,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!upload.ok)throw new Error(`Upload failed (${upload.status})`);const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))].map(x=>x.toString(16).padStart(2,'0')).join('');await api(`/api/runs/${state.runId}/upload-complete`,{method:'POST',body:JSON.stringify({bytes:file.size,sha256:digest})});state.session=null;openRun(state.runId)}catch(x){fail(x)}finally{cancel.hidden=true}});
document.querySelector('#cancel-upload').addEventListener('click',async()=>{if(state.session)await fetch(state.session,{method:'DELETE'}).catch(()=>{});if(state.runId)await api(`/api/runs/${state.runId}/cancel`,{method:'POST',body:'{}'}).catch(()=>{});state.session=null;show('submit')});
const durationLabel=range=>{if(!range)return'';const seconds=Math.max(0,range.end-range.start)/1000;return`${(range.start/1000).toFixed(1)}–${(range.end/1000).toFixed(1)}s · ${seconds.toFixed(1)}s track`};
const qualityLabel=quality=>{const count=quality?.observation_count;if(!count)return'';return`${count} observation${count===1?'':'s'}`};
async function groups(){try{const{body,response}=await api(`/api/runs/${state.runId}/face-groups`);state.etag=response.headers.get('ETag');const root=document.querySelector('#faces');root.replaceChildren();body.groups.forEach((g,i)=>{const label=document.createElement('label');label.className='face';label.innerHTML=`<input type="checkbox" value="${g.group_id}"><img alt="Detected person ${i+1}" src="${g.preview_url}"><strong>Person ${i+1}</strong>`;label.querySelector('input').checked=g.selected;const details=document.createElement('span');details.className='face-meta';details.textContent=[durationLabel(g.time_range_ms),qualityLabel(g.quality)].filter(Boolean).join(' · ')||'Image detection';label.append(details);root.append(label)});show('selection')}catch(e){fail(e)}}
const setAllFaces=checked=>document.querySelectorAll('#faces input[type="checkbox"]').forEach(input=>{input.checked=checked});
document.querySelector('#select-all').addEventListener('click',()=>setAllFaces(true));document.querySelector('#clear-all').addEventListener('click',()=>setAllFaces(false));
document.querySelector('#selection-form').addEventListener('submit',async e=>{e.preventDefault();const group_ids=[...document.querySelectorAll('#faces input:checked')].map(x=>x.value);if(!group_ids.length)return;try{await api(`/api/runs/${state.runId}/face-selection`,{method:'PUT',headers:{'If-Match':state.etag},body:JSON.stringify({group_ids})});poll()}catch(x){fail(x)}});
async function results(){try{state.results=(await api(`/api/runs/${state.runId}/results`)).body;renderResults()}catch(e){fail(e)}}
function renderResults(){const root=document.querySelector('#candidate-groups');root.replaceChildren();state.results.groups.forEach((g,i)=>{const h=document.createElement('h3');h.textContent=`Selected person ${i+1}`;root.append(h);g.candidates.forEach(c=>{const a=document.createElement('article');a.className='candidate';a.innerHTML=`<div class="candidate-copy"><strong>${c.display_name||'Unnamed subject'}</strong><p>${(c.similarity*100).toFixed(1)}% similarity · rank ${c.rank}</p><div class="representatives">${c.representative_faces.map(f=>`<img src="${f.url}" alt="Representative face">`).join('')}</div><button class="secondary subject-link" data-id="${c.subject_id}">View subject gallery</button></div>`;root.append(a)})});show('results')}
function noFaces(){document.querySelector('#candidate-groups').innerHTML='<p>No faces were detected in this media.</p>';show('results')}
document.querySelector('#candidate-groups').addEventListener('click',async e=>{const b=e.target.closest('.subject-link');if(!b)return;try{const s=(await api(`/api/subjects/${b.dataset.id}`)).body;document.querySelector('#subject-detail').innerHTML=`<h2>${s.display_name||'Unnamed subject'}</h2><p>${s.source_count} sources · ${s.observation_count} observations</p><div class="representatives">${s.representative_faces.map(f=>`<img src="${f.url}" alt="Representative face">`).join('')}</div>`;show('subject')}catch(x){fail(x)}});
document.querySelector('#check-form').addEventListener('submit',e=>{e.preventDefault();openRun(document.querySelector('#check-id').value)});document.querySelector('#copy-id').addEventListener('click',()=>navigator.clipboard.writeText(state.runId));const cancel=async()=>{try{await api(`/api/runs/${state.runId}/cancel`,{method:'POST',body:'{}'});poll()}catch(e){fail(e)}};document.querySelector('#cancel-run').addEventListener('click',cancel);document.querySelector('#selection-cancel').addEventListener('click',cancel);document.querySelector('#retry-run').addEventListener('click',async()=>{try{await api(`/api/runs/${state.runId}/retry`,{method:'POST',body:'{}'});poll()}catch(e){fail(e)}});document.querySelector('#back-results').addEventListener('click',renderResults);document.querySelector('#error-home').addEventListener('click',()=>{history.replaceState({},'','/');show('submit')});document.querySelector('#new-run').addEventListener('click',()=>show('submit'));document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));const saved=location.pathname.match(/^\/runs\/([0-9a-f-]{36})$/i);if(saved)openRun(saved[1]);
